### ISSUE TITLE
В документации указана не та ветка.

### ISSUE THREAD

**Issue by atm24-pro** [alexborsch/telegram-bot-php#1]
Весь мозг себе выебал.
У тебя указан composer require irazasyed/telegram-bot-sdk ^2.0
Там не хватает некоторых методов.
Сейчас вышла 3 ветка.
composer require irazasyed/telegram-bot-sdk

За курс спасибо.

**Comment by sleleko** [comment]
Тоже задумался по поводу версии, но не долго. Прописал последнюю да и все.

**Comment by oborshch** [comment]
> Весь мозг себе выебал.
> У тебя указан composer require irazasyed/telegram-bot-sdk ^2.0
> Там не хватает некоторых методов.
> Сейчас вышла 3 ветка.
> composer require irazasyed/telegram-bot-sdk
> 
> За курс спасибо.

Спасибо за отзыв. Версия была актуальная на момент разработки. Всегда ведь можно обновится руками
